version: '3.8'

services:
  database:
    image: database:latest
    restart: on-failure
    build: ./database/sql

    ports:
      - '8080:8080'

    volumes:
      - ./server/:/usr/server/

    networks:
      - main_network

  nginx:
    image: nginx:latest
    build: ./database/sql/nginx
    ports:
      - '8080:80'
      - '443:443'

    networks:
      - main_network
    
    depends_on:
      - database

networks:
  main_network:
    driver: bridge

