version: '3.8'

services:
  server:
    image: server:latest
    restart: on-failure
    build: ./server

    ports:
      - '8080:8080'

    volumes:
      - ./server/:/usr/server/
    
    depends_on:
      - redis

    networks:
      - main_network

  redis:
    image: redis:latest
    build: ./database/redis

    ports: 
      - '6379:6379'

    volumes:
      - ./server/:/usr/database/redis

    networks:
      - main_network

networks:
  main_network:
    driver: bridge

