name: Testing_redis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: "redis:latest"
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/database/redis/build/tests ${{github.workspace}}/database/redis/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/database/redis/build/tests --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/database/redis/build/tests
      run: ctest -C ${{env.BUILD_TYPE}}